### PR TITLE
Release rsconnect-python 1.20.0

### PR DESCRIPTION
**Pull request by dbkegley**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbkegley** [comment]
@conda-forge-admin, please rerender

**Review by tdstein — APPROVED** [review]

**Review by tdstein — CHANGES_REQUESTED** [review]
Need to update the sha256

**Comment by tdstein** [comment]
It's e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

**Comment by dbkegley** [comment]
@conda-forge-admin, please rerender

**Review by tdstein — APPROVED** [review]

**Comment by dbkegley** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
