### PR TITLE
use 1.23.0

### PR DESCRIPTION
**Pull request by aronatkins**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aronatkins** [comment]
@conda-forge-admin please rerender

**Comment by aronatkins** [comment]
@conda-forge-admin, please rerender

**Comment by mmarchetti** [comment]
It looks like `version` still needs to be bumped in meta.yaml (or was reverted by the re-render?)

**Comment by aronatkins** [comment]
Removed the maintainer update; that arrives separately, in https://github.com/conda-forge/rsconnect-python-feedstock/pull/37

**Comment by aronatkins** [comment]
@conda-forge-admin, please rerender

**Comment by aronatkins** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
